### ISSUE TITLE
transform_image function

### ISSUE THREAD

**Issue by kli-casia** [jesu9/VGGFeatExtract#1]
Hi,
In transform_image function

```
if img.shape[0] < img.shape[1]:
    # Note: OpenCV uses width first...
    dsize = (int(np.floor(float(image_dim)*img.shape[1]/img.shape[0])), image_dim)
  else:
    dsize = (image_dim, int(np.floor(float(image_dim)*img.shape[0]/img.shape[1])))
```

I don't think opencv uses width first. 
http://stackoverflow.com/questions/19098104/python-opencv2-cv2-wrapper-get-image-size
Is there something wrong with this code?
Thank you.

**Comment by jesu9** [comment]
Hi @kli-nlpr 
dsize is used for cv2.resize(), which takes width as the first argument.
http://docs.opencv.org/modules/imgproc/doc/geometric_transformations.html#resize

**Comment by kli-casia** [comment]
Hi, @jesu9  Thank you for your help. I will close this issue
